version: '3.7'

services:
  backend:
    image: tikiwiki/tikiwiki:20.x
    depends_on:
      - db
    environment:
      - TIKI_DB_USER=tiki
      - TIKI_DB_PASS=wiki
      - TIKI_DB_NAME=tikiwiki
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
    volumes:
      - tiki_files:/var/www/html/files
      - tiki_img_trackers:/var/www/html/img/trackers
      - tiki_mod_cache:/var/www/html/modules/cache
      - tiki_temp:/var/www/html/temp
      - tiki_sessions:/var/www/sessions
      - tiki_img_wikiup:/var/www/html/img/wiki_up
      - tiki_storage:/var/www/html/storage
      - tiki_img_wiki:/var/www/html/img/wiki
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    networks:
      - internal
      - global-services_default
    configs:
      - source: php_opcache
        target: /usr/local/etc/php/conf.d/opcache.ini
        mode: 0644
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost"]
#      interval: 1m30s
#      timeout: 10s
#      retries: 3
#      start_period: 40s

  db:
    image: mariadb
    environment:
      - MYSQL_USER=tiki
      - MYSQL_PASSWORD=wiki
      - MYSQL_DATABASE=tikiwiki
      - MYSQL_ROOT_PASSWORD=tikiwiki
      - TERM=dumb
    volumes:
      - data:/var/lib/mysql
    networks:
      - internal

volumes:
  data:
  tiki_files:
  tiki_img_trackers:
  tiki_mod_cache:
  tiki_temp:
  tiki_sessions:
  tiki_img_wikiup:
  tiki_storage:
  tiki_img_wiki:

networks:
  internal:
  global-services_default:
    external: true

configs:
  php_opcache:
    file: ./config-php-opcache.ini
