version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certificates:/etc/nginx/certs
      - nginx-vhostd:/etc/nginx/vhost.d/
      - nginx-htdocs:/usr/share/nginx/html
      - nginx-dhparam:/etc/nginx/dhparam
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    ports:
      - 80:80
      - 443:443

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - DEFAULT_EMAIL=fabio.montefuscolo@gmail.com
    volumes:
      - nginx-certificates:/etc/nginx/certs
      - nginx-vhostd:/etc/nginx/vhost.d/
      - nginx-htdocs:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nginx-certificates:
  nginx-vhostd:
  nginx-htdocs:
  nginx-dhparam:

